database:
  # the name of your JDBC driver
  driverClass: org.h2.Driver

  # the JDBC URL
  url: jdbc:h2:mem:transactions;DB_CLOSE_DELAY=-1
  #url: jdbc:h2:/home/pavel/project/db

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 32

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false
